### ISSUE TITLE
Task status update not reflecting the value

### ISSUE THREAD

**Issue by yubinkarki** [yubinkarki/Projecter#9]
When going over the the **Tasks** section for a user via the sidebar, the user can click on the **Details** button to change the status of the task from a dropdown. However, upon selecting a new option, the value isn't reflecting in the input field on the first render. Only after clicking away from the modal and re-opening it, does the value update.

**Comment by yubinkarki** [comment]
https://user-images.githubusercontent.com/36847479/196710819-92a64bfd-d3ad-4e28-940d-2534a5c626c7.mp4

**Comment by ozair-dev** [comment]
Hi, I didn't run the code locally but I think I found yout fix
https://github.com/yubinkarki/Projecter/blob/403b8c51268bd983ab452afa38cabcdc9f0a82f8/projecter_frontend/src/components/task/UserTaskModal.jsx#L128-L137
Here you need to pass ```value={statusSelectOption}``` and maybe you can remove the **defaultValue** prop

**Comment by ozair-dev** [comment]
Let me know if it fixes it.

**Comment by yubinkarki** [comment]
Hey ozair, thanks for the response. Unfortunately, the solution you provided didn't work.

**Comment by ozair-dev** [comment]
ok, I'll then have to setup this project on my machine.
Am i gonna have to need the Admin/PM/employee credentials for login?

**Comment by ozair-dev** [comment]
And can you send me the snippet of your code? just so I can confirm

**Comment by yubinkarki** [comment]
Here's a [link to the solution](https://www.youtube.com/watch?v=uiQRr4k3xPs) you mentioned. I had to upload it on YT as GH didn't let me upload a large file.

**Comment by yubinkarki** [comment]
To run the project, you need to create a .env file at the root of the projecter_backend folder. Use this DB url to get a read access which should work in order to look around.
```
DB = "mongodb+srv://admin:-ezrdMxTNqE4Vv8@projecter.vt3wa4s.mongodb.net/main?retryWrites=true&w=majority"
PORT = 3000
JWT_KEY = fjkerherfui34euicd8932DJFERFH43EFERJKJEH
JWT_EXPIRE = 5d
```

**Comment by ozair-dev** [comment]
Uncomment this code
![Screenshot from 2022-11-01 10-28-34](https://user-images.githubusercontent.com/65649182/199165407-04f5d0df-633b-49a3-9be4-34d0183da334.png)
 
If still this does not work, then remove it's **disabled** prop

**Comment by yubinkarki** [comment]
That part is to just show the extra option. I don't think it has anything to do with the data not showing the first time.

**Comment by ozair-dev** [comment]
Ok, lemme run it locally

**Comment by yubinkarki** [comment]
Here's the contents of the .env file with DB READ access.
```
DB = "mongodb+srv://guest:12345@projecter.vt3wa4s.mongodb.net/main?retryWrites=true&w=majority"
PORT = 3000
JWT_KEY = fjkerherfui34euicd8932DJFERFH43EFERJKJEH
JWT_EXPIRE = 5d
```

User credentials
- email: ky@gmail.com
- pw: 22222

**Comment by ozair-dev** [comment]
> That part is to just show the extra option. I don't think it has anything to do with the data not showing the first time
It sure does actually. Check the PR
